### ISSUE TITLE
Drag & drop not working well when using less than 5 slides

### ISSUE THREAD

**Issue by MatthewRuddy** [easingslider/easing-slider#2]
When using 4 or less slides, the drag and drop re-ordering isn't working very well or sometimes at all.

Likely related to CSS (possibly padding?) and jQuery sortables plugin parameters.

**Comment by mpsparrow** [comment]
You could try implementing this. http://jqueryui.com/sortable/#display-grid

Which file(s) would I find the current sortable code?

**Comment by mpsparrow** [comment]
Have you looked at the link above?

**Comment by MatthewRuddy** [comment]
Yes, we're actually currently using this.

The code can be found in `js/editor-pages.js` within the Easing Slider plugin folder.

**Comment by mpsparrow** [comment]
How about this HTML5 grid. https://github.com/farhadi/html5sortable

**Comment by MatthewRuddy** [comment]
Just gave this a quick try, but can't get it to work in the WordPress admin area :-1:

Might try again at a later stage, but I'd wonder if it would break the other jQuery reliant code if both jQuery sortable and HTML sortable were loaded on the same page.

**Comment by mpsparrow** [comment]
There is no end to jQuery, JavaScript, or HTML5 sortable grids. Just search it on Google. https://www.google.ca/#q=grid+sortable+code

**Comment by MatthewRuddy** [comment]
That's not really the issue - conflicts with jQuery sortables, which is included in WordPress and loaded by many plugins, is the main issue. Often, plugins will load their admin scripts on all pages incorrectly, rather than just their own.

If a jQuery error gets thrown because of us using a different sortables script, the admin will break and users will be unhappy. Thorough testing is needed, it's much more than just implementing something that works :)

**Comment by MatthewRuddy** [comment]
Should be much improved with [this commit](https://github.com/easingslider/easing-slider/commit/311df90434d23fa531d884aef4c83052e21a15cd). Seems to be better throughout testing. Going to close this issue but feel free to get back in contact if anyone experiences issues.

**Comment by mpsparrow** [comment]
Awesome! I will test it later today to see how it works.
