### ISSUE TITLE
remove admin screen menu once read

### ISSUE THREAD

**Issue by airplanenoise** [easingslider/easing-slider#23]
Hi, 

wondering if you would consider removing the side menus that appear under Dashboard of WP after installing Easing Slider... Would much prefer accessing that from a settings screen below Easing Slider. This is an issue for us as we develop themes and admin themes with very customized and minified back-office views and those Easing Slider menus (welcome to easing slider, getting started with easing slider, the people that built easing slider...) get in the way. 

happy to pay or upgrade if needed. 

thanks, 

Kaz

**Comment by MatthewRuddy** [comment]
Overlooked this but should be sorted as we've removed the welcome screens temporarily from v3.0.0 onwards. Should feature again when I've capacity to revisit.
