### ISSUE TITLE
Costumizations not working

### ISSUE THREAD

**Issue by michelmany** [easingslider/easing-slider#24]
The Customize page is not working, so I can't change the path of Next & previous arrows and pagination icons. When I deploy my website it's not appearing because you don't use absolute path. I'm using chrome or firefox but I can't click on buttons (page=easingslider_manage_customizations).. Thanks

**Comment by MatthewRuddy** [comment]
Have removed from v3.0.0 onwards. I hope to redevelop the customiser and make it available again in the future, but right now I've not got the capacity to do so. Hopefully will soon.
