### ISSUE TITLE
Slider setting arbitrary width that is too small

### ISSUE THREAD

**Issue by cdpritcha** [easingslider/easing-slider#25]
The slider sets a width of 640px !important inline. The slider images are 960px and the container the slider sits inside is 980px. The !important makes it impossible to override in external CSS.

Why is the slider being set to 640px and how can I fix it?

**Comment by MatthewRuddy** [comment]
Slider dimensions should be set in the admin panel only, not modified using CSS. The !important rulings are to ensure consistency across themes and prevent conflicts with other plugins.

Often themes/plugins apply vague CSS rulings that can add margins, paddings, borders, etc, undesirably to slider elements and break the layout. Hence the strict nature of the CSS applied.
